module.exports = [

	"all",

	/* Positioning */
	"position",
	"top",
	"right",
	"bottom",
	"left",
	"z-index",

	/* Layout */
	"opacity",
	"visibility",
	"display",
	"grid",
	"grid-template-columns",
	"grid-template-rows",
	"grid-template-areas",
	"grid-template",
	"grid-column-gap",
	"grid-row-gap",
	"grid-gap",
	"justify-items",
	"place-items",
	"place-content",
	"grid-auto-columns",
	"grid-auto-rows",
	"grid-auto-flow",
	"grid-column-start",
	"grid-column-end",
	"grid-row-start",
	"grid-row-end",
	"grid-column",
	"grid-row",
	"grid-area",
	"justify-self",
	"place-self",
	"flex",
	"flex-align",
	"flex-basis",
	"flex-direction",
	"flex-wrap",
	"flex-flow",
	"flex-shrink",
	"flex-grow",
	"flex-order",
	"flex-pack",
	"align-content",
	"align-items",
	"align-self",
	"justify-content",
	"order",
	"table-layout",
	"empty-cells",
	"caption-side",
	"border-spacing",
	"border-collapse",
	"content",
	"float",
	"clear",
	"columns",
	"column-count",
	"column-fill",
	"column-gap",
	"column-rule",
	"column-rule-width",
	"column-rule-style",
	"column-rule-color",
	"column-span",
	"column-width",
	"orphans",
	"widows",
	"break-after",
	"break-before",
	"break-inside",
	"page-break-after",
	"page-break-before",
	"page-break-inside",
	"line-break",
	"white-space", // normal | pre | nowrap | pre-wrap | pre-line | break-spaces
	"tab-size",

	/* Box-model */
	"box-sizing",
	"width",
	"min-width",
	"max-width",
	"height",
	"min-height",
	"max-height",
	"overflow",
	"overflow-x",
	"overflow-y",
	"-webkit-overflow-scrolling",
	"-ms-overflow-x",
	"-ms-overflow-y",
	"-ms-overflow-style",
	"box-decoration-break",
	"clip",
	"clip-path",
	"margin",
	"margin-top",
	"margin-right",
	"margin-bottom",
	"margin-left",
	"padding",
	"padding-top",
	"padding-right",
	"padding-bottom",
	"padding-left",
	"border",
	"border-color",
	"border-style",
	"border-width",
	"border-top",
	"border-top-color",
	"border-top-style",
	"border-top-width",
	"border-right",
	"border-right-color",
	"border-right-style",
	"border-right-width",
	"border-bottom",
	"border-bottom-color",
	"border-bottom-style",
	"border-bottom-width",
	"border-left",
	"border-left-color",
	"border-left-style",
	"border-left-width",
	"border-radius",
	"border-top-left-radius",
	"border-top-right-radius",
	"border-bottom-right-radius",
	"border-bottom-left-radius",
	"border-image",
	"border-image-source",
	"border-image-slice",
	"border-image-width",
	"border-image-outset",
	"border-image-repeat",
	"outline",
	"outline-width",
	"outline-style",
	"outline-color",
	"outline-offset",
	"stroke",
	"box-shadow",
	"list-style",
	"list-style-position",
	"list-style-type",
	"list-style-image",
	"transform",
	"transform-origin",
	"transform-style",
	"backface-visibility",
	"perspective",
	"perspective-origin",
	"zoom",
	"filter",
	"mix-blend-mode", // normal | multiply | screen | overlay | darken | lighten | color-dodge | color-burn | hard-light | soft-light | difference | exclusion | hue | saturation | color | luminosity
	"-ms-interpolation-mode",

	/* Visual */
	"color",
	"background",
	"background-color",
	"background-image",
	"background-repeat",
	"background-attachment",
	"background-position",
	"background-position-x",
	"background-position-y",
	"background-clip",
	"background-origin",
	"background-size",
	"background-blend-mode", // normal | multiply | screen | overlay | darken | lighten | color-dodge | color-burn | hard-light | soft-light | difference | exclusion | hue | saturation | color | luminosity
	"fill",

	/* Typography */
	"font",
	"font-family",
	"font-size", // xx-small | x-small | small | medium | large | x-large | xx-large | xxx-large | smaller | larger | <length> | <percentage>
	"font-style", // normal | italic | oblique <angle>{0,2}
	"font-weight", // normal | bold | bolder | lighter | <number>{100,900}
	"font-variant", // normal | none | small-caps
	"font-variant-alternates",
	"font-variant-caps",
	"font-variant-east-asian",
	"font-variant-ligatures",
	"font-variant-numeric",
	"font-variant-position",
	"font-size-adjust", // none | <number>
	"font-stretch", // normal | ultra-condensed | extra-condensed | condensed | semi-condensed | semi-expanded | expanded | extra-expanded | ultra-expanded | <percentage>
	"font-feature-settings", // normal | <string> | <integer> | on | off
	"font-kerning", // auto | normal | none
	"font-effect",
	"font-emphasize",
	"font-emphasize-position",
	"font-emphasize-style",
	"font-smooth", // auto | never | always | <length>
	"line-height", // normal | <number> | <length> | <percentage>
	"text-align", // start | end | left | right | center | justify | match-parent
	"text-align-last", // auto | start | end | left | right | center | justify
	"text-emphasis",
	"text-emphasis-color",
	"text-emphasis-style", // none | filled | open | dot | circle | double-circle | triangle | sesame | <string>
	"text-emphasis-position", // over | under | right | left
	"text-decoration",
	"text-decoration-color",
	"text-decoration-line", // none | underline | overline | line-through | blink | spelling-error | grammar-error
	"text-decoration-style", // solid | double | dotted | dashed | wavy
	"text-decoration-thickness", // auto | from-font | <length>
	"text-indent", // <length> | <percentage>
	"text-justify",
	"text-outline",
	"-ms-text-overflow",
	"text-overflow", // clip | ellipsis | <string>
	"text-overflow-ellipsis",
	"text-overflow-mode",
	"text-shadow",
	"text-transform", // none | capitalize | uppercase | lowercase | full-width | full-size-kana
	"text-wrap", // wrap | nowrap | balance | stable | pretty
	"hyphens",
	"-webkit-text-size-adjust", // none | auto | <percentage>
	"-ms-text-size-adjust",
	"letter-spacing",
	"-ms-word-break",
	"word-break", // normal | break-all | keep-all | break-word
	"word-spacing", // normal | <length> | <percentage>
	"-ms-word-wrap",
	"word-wrap", // normal | break-word
	"overflow-wrap", // normal | break-word | anywhere
	"vertical-align", // baseline | sub | super | text-top | text-bottom | middle | top | bottom | <percentage> | <length>
	"quotes",
	"direction",
	"unicode-bidi",

	/* Interactions/Interfaces */
	"cursor",
	"pointer-events",
	"-ms-touch-action",
	"touch-action",
	"resize",
	"user-select",
	"appearance",
	"caret-color",

	/* Animations */
	"animation",
	"animation-name",
	"animation-duration",
	"animation-play-state",
	"animation-timing-function",
	"animation-delay",
	"animation-iteration-count",
	"animation-direction",
	"animation-fill-mode",
	"transition",
	"transition-delay",
	"transition-timing-function",
	"transition-duration",
	"transition-property",
	"will-change",

	/* Math */
	"counter-increment",
	"counter-reset",

];